/**
 * 
 */
package zephyr;

/**
 * @author colep
 *
 */
public class User {
	private String name;
	private String id;
	
	public User(String name) {
		this.name = name;
		this.id = "autogeneratedIdThatMustBeUnique";
	}
	
	public String getName() {
		return this.name;
	}
	
	public String GetId() {
		return id;
	}
	
}
